server:
  port: 8080

spring:
  application:
    name: user
  kafka:
    producer:
      bootstrap-servers:
        - broker:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mail:
  confirmationTime: 15m

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
