server:
  port: 8080

spring:
  cloud:
    config:
      label: main
      profile: dev
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 3000
        max-interval: 10000
        multiplier: 1.3
  application:
    name: user
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#      product:
#        connectTimeout: 5000
#        readTimeout: 5000

