server:
  port: 8080

spring:
  application:
    name: user

mail:
  subject: Banking System Demo - User account confirmation
  senderEmail: bsd@example.com
  encoding: utf-8
  confirmationTime: 15m

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka