server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jakubgrajber/Banking-System-Demo-Config
          search-paths:
            - config*

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka