server:
  port: 8081

spring:
  cloud:
    config:
      label: main
      profile: dev
  application:
    name: notifications
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

